### PR TITLE
Updates html_tag

### PR DESCRIPTION
**Pull request by tonytlwu**

### CODE REVIEW

**Comment by seromenho** [comment]
@tonytlwu Could you please provide some description.
What's the reason of this?

**Comment by tonytlwu** [comment]
@seromenho Because it's incorrectly using a `span` to output the content instead of `div`, it's determining the output as an inline output. It should've been with a `div` as a block output.

**Comment by tonytlwu** [comment]
...otherwise it messes up the drag and drop UI

**Comment by seromenho** [comment]
👍

**Pull request merged**
